name: Some Workflow
on: push

env:
  VARIABLE: value

jobs:
  first:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        id: ci-job-token
        with:
          script: |
            const token = process.env['ACTIONS_RUNTIME_TOKEN']
            const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
            console.log({ token, runtimeUrl })

