name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: check node version
        run: node -v
      - name: try to read file without checkout
        run: cat README.md
  another_job:
    # needs: dump_contexts_to_log
    runs-on: ubuntu-latest
    steps:
      - name: prepare folder
        run: mkdir -p path/to/artifact
      - name: produce artifact
        run: echo '${{ toJSON(github) }}' > path/to/artifact/world.txt
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
